version: '3.8'

services:
  flask-app:
    build: .
    container_name: filer
    ports:
      - "5000:5000"
    environment:
      - HOST_NAME=${HOST_NAME}
      - DISKS_JSON=${DISKS_JSON}
  restart: unless-stopped
